# Generated by Django 5.2.6 on 2025-10-04 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('pass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('completed_pass', models.BooleanField()),
                ('potential_assist', models.BooleanField()),
                ('turnover', models.BooleanField()),
                ('ball_start_loc_x', models.FloatField()),
                ('ball_start_loc_y', models.FloatField()),
                ('ball_end_loc_x', models.FloatField()),
                ('ball_end_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=25)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
            ],
            options={
                'db_table': 'passes',
            },
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('shot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('shooting_foul_drawn', models.BooleanField()),
                ('shot_loc_x', models.FloatField()),
                ('shot_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=25)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
            ],
            options={
                'db_table': 'shots',
            },
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='app.teams'),
        ),
        migrations.CreateModel(
            name='Turnovers',
            fields=[
                ('turnover_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tov_loc_x', models.FloatField()),
                ('tov_loc_y', models.FloatField()),
                ('action_type', models.CharField(max_length=25)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.players')),
            ],
            options={
                'db_table': 'turnovers',
            },
        ),
    ]
